---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xindong.
--- DateTime: 2021/9/18 21:04
---

local server_common = require 'base'

require 'base.isolation'

return server_common