base.tsc.CLASSES = {
    Actor = require 'base.actor'.Actor,
    UnitBuff = require 'base.buff'.UnitBuff,
    Buff = require 'base.buff'.Buff,
    Channeler = require 'base.channeler'.Channeler,
    Channeled = require 'base.channeler'.Channeled,
    RegionCircle = require 'base.circle'.RegionCircle,
    CmdResult = require 'base.cmd_result'.CmdResult,
    DamageInstance = require 'base.damage'.DamageInstance,
    EffectParam = require 'base.eff_param'.EffectParam,
    EffectParamShared = require 'base.eff_param'.EffectParamShared,
    HealInstance = require 'base.heal'.HealInstance,
    Inventory = require 'base.inventory'.Inventory,
    Slot = require 'base.inventory'.Slot,
    Item = require 'base.item'.Item,
    Line = require 'base.line'.Line,
    Player = require 'base.player'.Player,
    Point = require 'base.point'.Point,
    ScreenPos = require 'base.position'.ScreenPos,
    RegionRect = require 'base.rect'.RegionRect,
    Response = require 'base.response'.Response,
    ResponseDamage = require 'base.response'.ResponseDamage,
    ResponseMissileImpact = require 'base.response'.ResponseMissileImpact,
    ResponseEffectImpact = require 'base.response'.ResponseEffectImpact,
    ResponseSpell = require 'base.response'.ResponseSpell,
    ResponseBuff = require 'base.response'.ResponseBuff,
    ResponseUnit = require 'base.response'.ResponseUnit,
    ScenePoint = require 'base.scene_point'.ScenePoint,
    Skill = require 'base.skill'.Skill,
    Cast = require 'base.skill'.Cast,
    Snapshot = require 'base.snapshot'.Snapshot,
    TargetFilters = require 'base.target_filter'.TargetFilters,
    Team = require 'base.team'.Team,
    Timer = require 'base.timer'.Timer,
    Trigger = require 'base.trigger'.Trigger,
    Unit = require 'base.unit'.Unit,
    Region = require 'base.utility'.Region,
    Target = require 'base.utility'.Target,
    Mover = require 'base.utility'.Mover
}

function base.force_as(item)
    return item
end