---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xindong.
--- DateTime: 2022/1/8 14:55
---

debug.getregistry = nil
debug.getupvalue = nil
debug.setlocal = nil
debug.getlocal = nil
debug.upvaluejoin = nil
debug.sethook = nil
debug.setupvalue = nil
debug.setuservalue = nil
debug.upvalueid = nil
debug.gethook = nil

-- c++里面用的是real_package, 这里包装一下
local raw_package = _G.package
_G.package = setmetatable({}, {
    __newindex = function(self, key, value)
        if key == 'path' then
            assert(type(value) == 'string')
            local li = util.split(value, ';')
            for _, sub in ipairs(li) do
                if sub:find('[.][.]') or sub:find('^[\\w\\d]+:') or sub:find('^/') then
                    error(('set package.path with an invalid string: %s'):format(sub))
                end
            end
        end
        raw_package[key] = value
    end,
    __index = function(self, key)
        return raw_package[key]
    end
})